#!/bin/bash

#make -j4 DEBUG_DIAGNOSTICS=t TILES=t GAME="crawlDebug" SAVEDIR="/t/crawl/testSaves" debug

v="$1"
source buildCommon 

unset success
while true; do
	cd $code || break

    set -xv
    nice make -j${J:-4} TARGET_OS_MACOSX=t WEBTILES=t FULLDEBUG=true GAME="crawlTest" SAVEDIR="/t/crawl/testSaves" debug test || break
    set +xv
    #nice make -j${J:-4} TILES=t TARGET_OS_MACOSX=true GAME="crawlDebug" SAVEDIR="/t/crawl/testSaves" debug-lite test || break

	success=true
    break
done

if [ "$success" ]; then
	echo "Successful."
else
	echo "Failed!"
	exit 1
fi

