#!/bin/bash

#make -j4 DEBUG_DIAGNOSTICS=t TILES=t GAME="crawlDebug" SAVEDIR="/t/crawl/testSaves" debug

source buildCommon 

unset success
while true; do
	cd $code || break
    #debug=debug
    debug=

    #nice make -j${J:-4} NOASSERTS=True TILES=t GAME="crawlDebug" SAVEDIR="/t/crawl/testSaves" $debug || break
    set -xv
    nice make -j${J:-4} TILES=t GAME="crawlDebug" SAVEDIR="/t/crawl/testSaves" $debug || break
    set +xv

	success=true
    break
done

if [ "$success" ]; then
	echo "Successful."
else
	echo "Failed!"
	exit 1
fi

