#!/bin/bash

source common 

unset success
while true; do
	mkdir -p $web/bin || break
	touch $web/bin/crawl $web/bin/crawl.old
	cd $web/bin || break
	while true; do
		rm crawl.old && break
		echo "Failed, but will retry in a min..."
		sleep 60
	done
	mv crawl crawl.old || break
	cd $code || break

	nice make -j3 prefix=${web} GAME="crawl" USE_DGAMELAUNCH=y WEBTILES=y install || break

	success=true
    break
done

if [ "$success" ]; then
	echo "Successful."
else
	echo "Failed!"
	exit 1
fi

