#!/bin/bash

source common 

make="nice make -j2 NOASSERTS=True prefix=${web} GAME=\"crawl.new\" USE_DGAMELAUNCH=y WEBTILES=y"

unset success
while true; do
	mkdir -p $web/bin || break
	touch $web/bin/crawl $web/bin/crawl.old
	cd $web/bin || break

	cd $code || break
	$make debug-lite || break
	cd $web/bin || break

	while true; do
		rm crawl.old && break
		echo "Failed, but will retry in a min..."
		sleep 60
	done
	cd $code || break

	$make debug-lite install || break

	cd $web/bin || break
	mv crawl crawl.old || break
	mv crawl.new crawl || break

	success=true
    break
done

if [ "$success" ]; then
	echo "Successful."
else
	echo "Failed!"
	exit 1
fi

