#!/bin/bash

if [ ! "$commonSourced" ]; then

if [ ! "$1" ]; then
	echo "Usage: $0 {tag to update to}"
	exit 1
fi

unset keep debug local nomore version
while true; do

    case "$1" in
        debug)
            debug=true
            shift
            continue
            ;;
        local)
            local_code=true
            shift
            continue
            ;;
        keep)
            keep=true
            shift
            continue
            ;;
        *)
            if [ ! "$1" ]; then
                nomore=true
                break
            fi
            if [ "$version" -a "$1" ]; then
                echo "I already caught $version for version string. Invalid flag: $1"
                exit 1
            fi
            version="$1"
            shift
            break
            ;;
    esac

    [ "$nomore" ] && break
done

if [ ! -f localConfig ]; then
	echo "Make a localConfig out of localConfig.example before running this."
	exit 1
fi

source localConfig || exit 1
commonWeb="$web"

if [ ! "$version" ]; then
	echo "Missing version"
	exit 1
fi

web="$web/$version"

if [ ! "$code1" ]; then
	echo "Missing code1"
	exit 1
fi

middle_dir=${base_repo}_web
if [ ! "$local_code" ]; then
    middle_dir="${base_repo}_web-$version"
fi
code="$code1/${middle_dir}/$code2"

echo code=$code
if [ ! -d "$code" ]; then
    echo "Cloning repository..."
	cd "$code1" || exit 1
	git clone https://github.com/jeremygurr/$base_repo.git -b "$version" "${middle_dir}" || exit 1
fi

if [ ! -f "$code/contrib/sqlite/Makefile" ]; then
	cd "$code" || exit 1
    echo "Updating submodules..."
	git submodule update --init || exit 1
    cd contrib || exit 1
    make || exit 1
fi

cd "$code" || exit 1

if [ ! "$keep" -a ! "$local_code" ]; then
	git checkout "$version" || exit 1
	git pull || exit 1
	git checkout "$version" || exit 1
fi

# usage: hydrate {from file} {to file}
#   will replace variables in from file with values of variables defined in current shell environment
unset hydrate
hydrate() {
local from to line
from="$1"
shift
to="$1"
local returnValue=0
if [ -f "$to" ]; then
	echo "File already exists: $to"
	return 1
fi
while true; do
    if [ ! -f "$from" ]; then
        echo "Missing file: $from"
        fail
    fi
    local OIFS="$IFS"
    IFS=$'\n'
    while read -r line; do
        line="${line//\"/\\\"}"
        eval "echo \"$line\"" >>$to || fail
    done < $from
    break
done
IFS="$OIFS"
return $returnValue
}

commonSourced=true
fi
