#!/bin/bash

source /etc/profile
source ~/shortcuts.sh

version=${version:-v1.5.2}
base_folder="/Users/jeremy/Library/Application Support/Dungeon Crawl Stone Soup: Circus Animals"
save_folder="$base_folder/saves"

user=$1
if [ ! "$user" ]; then
    echo "Usage: $0 {user name}"
fi

set -xv
rm "$save_folder/.$user.cs"
rcpp $ple:/var/crawl/$version/.$user.cs "$save_folder/" || exit 1
rm "$base_folder/macro.txt"
rcpp $ple:/var/crawl/rcs/$user.macro "$base_folder/macro.txt" | exit 1
rm ~/init.txt 
rcpp $ple:/var/crawl/rcs/$user.rc ~/init.txt | exit 1

set +xv
echo "Successfully downloaded save file for $user."
