#!/bin/bash
source lib/global
source lib/roots

return_value=0 
while true; do
    unset fatal_error
    if [ "$1" == debug ]; then
        shift
        set -xv
    fi
	fix crawl_tiki

	end_loop

	if [ ! "$(pgrep mysqld)" ]; then
		err "Mysql isn't running yet. So we'll start it."
		service mysql start || fail
	fi

	break
done

show_errors

exit $return_value

