#!/bin/bash
source lib/global
source lib/need

returnValue=0 
while true; do
	need crawl_tiki
	break

	if [ ! "$(pgrep mysqld)" ]; then
		err "Mysql isn't running yet. So we'll start it."
		service mysql start || fail
	fi

	break
done

exit $returnValue

