#!/bin/bash

v="$1"

J="${J:-2}" source common 

cd "$code" || exit 1

if [ ! "$keep" ]; then
	git checkout "$v" || exit 1
	git pull || exit 1
fi

cd $crawlserver || exit 1
source buildWeb "$@" || exit 1

webTarget="$web/webserver"

cd $code || exit 1
rsync -a webserver/ ${webTarget}/ || exit 1

cd $crawlserver || exit 1
#rsync -a ${webTarget}/templates/ $web/templates/ || exit 1
#rsync -a ${webTarget}/static/ $web/static/ || exit 1
rsync -a banner.html ${webTarget}/templates/ || exit 1
rsync -a init.txt $commonWeb/ || exit 1
rsync -a init-player.sh $commonWeb/ || exit 1
rm /tmp/confg.py &>/dev/null
hydrate config.py.template /tmp/config.py || exit 1
mv /tmp/config.py ${webTarget}/ || exit 1

if [ "$user" != None ]; then
	chown -R crawl ${web} || exit 1
fi

