#!/bin/bash

source common

git pull || exit 1
source buildWeb || exit 1

cd $code || exit 1
rsync -a webserver/ ${web}/webserver/ || exit 1

cd $crawlserver || exit 1
rsync -a banner.html ${web}/webserver/templates/ || exit 1
rm /tmp/confg.py &>/dev/null
hydrate config.py.template /tmp/config.py || exit 1
mv /tmp/config.py ${web}/webserver/ || exit 1

if [ "$user" != None ]; then
	chown -R crawl ${web} || exit 1
fi

